### PR TITLE
Many fixes to resources + Bootstrap 4 support.

### PR DESCRIPTION
**Pull request by travist**

### CODE REVIEW

**Comment by StephenOTT** [comment]
@travist can you explain the bootstrap 4 support?

**Comment by travist** [comment]
This just adds support for some of the bootstrap 4 classes so that the forms render correctly with bootstrap 4. Bootstrap 3 is also supported since I just added the additional classes where they are needed. Example is adding ```card``` instead of ```panel```

**Comment by StephenOTT** [comment]
@travist this was brought over into formio.js core?  Would you consider the boostrap4 support as a beta? or was it added for all components and tested?

**Comment by travist** [comment]
It was implemented in a way to be reverse compatible, and implemented on all components. We ran through our typical test process using both Bootstrap 4 and Bootstrap 3 and they passed. Are you seeing an error?

**Comment by StephenOTT** [comment]
@travist no just asking.  And this was implemented into the formio.js level?

**Comment by travist** [comment]
Yes it was.

**Comment by StephenOTT** [comment]
Thank you

**Pull request merged**
